### ISSUE TITLE
"Submit a Link" button gets displaced when gallery is filtered

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#110]
This is a minor visual flaw, not a burning top priority!

When I select any filters in the External Links Gallery, for example [this one](https://projectpythia.org/pages/links/course.html) so that the "Return to Full Gallery" button appears, the "Submit a Link" button gets nudged downward and partially obscured by the gallery content.

It would better if that button stayed put in one place in all contexts.

**Comment by brian-rose** [comment]
This problem seems to be resolved with the new theme in #115.

**Comment by kmpaul** [comment]
With the merge of #115, I think this is resolved.
