### ISSUE TITLE
Rewrite & update the "About" content

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#116]
As mentioned in #115, regarding the new portal landing page, @brian-rose mentioned:

>  I think the paragraph under the "Project Pythia" heading is too verbose, seeing as it's the first thing people see when they hit the page. I think we can come up something snappier that describes the project in a few short catchphrases, and leave the details to the "About" page.

and further:

> The "About" page needs updating to better reflect where we are and where we are aiming with our content.

With the merge of #115, I am moving these suggestions to this issue.

**Comment by brian-rose** [comment]
As discussed at today's EWG, I will take a stab at these changes in a new PR.

**Comment by brian-rose** [comment]
I am re-committing myself (again) to getting this done, and making sure that the link to Pangeo is spelled out on the landing page.

**Comment by brian-rose** [comment]
Can we close this with the merger of #215, and further landing-page improvements in #227?
