### ISSUE TITLE
Responsive Gallery: Broken display on small screens

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#121]
**What happened**:

On small screens, the gallery does not look good.  You can see the problem here:

<img width="375" alt="Screen Shot 2021-06-22 at 4 13 51 PM" src="https://user-images.githubusercontent.com/11411331/123006686-4a881a00-d375-11eb-8c5c-0719e65579fb.png">

and here:

<img width="378" alt="Screen Shot 2021-06-22 at 4 17 52 PM" src="https://user-images.githubusercontent.com/11411331/123007041-cd10d980-d375-11eb-9539-67f677a130f2.png">

**What you expected to happen**:

The page should look good on all screen sizes.

**Minimal Complete Verifiable Example**:

Go to the gallery and reduce the width of your browser to as small as it will go.  Or look at it on your phone.

**Anything else we need to know?**:

I think we need some `@media` rules that change the CSS (`_static/custom.css`) depending on screen width.  Namely, on small screens I think it should display as:

- Thumbnail image above the card content, 100% width
- Modal image removed?  Might need to make the modal window scrollable?

**Environment**:

- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by ktyle** [comment]
Is there any way other than trial and error to determine what the minimum width in pixels value should be? Using Chrome's Developer Tools and turning on the "Device Mode" (icon to do this looks like a mobile device), and then adjusting the width, it seems that this value is 480 px ... at least based on what we currently have in the gallery.

**Comment by kmpaul** [comment]
Yeah.  That's what I do, actually.  I take a look at the page on the Chrome Developer Tools "Device Mode" and look at it in various phone sizes.  I think I'm actually almost done with a draft that fixes this issue.
