### ISSUE TITLE
Multiple gallery filters

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#125]
Currently our [Resource Gallery](https://projectpythia.org/gallery.html) uses tags under three different categories (Domains, Formats, Packages) for filtering.

How feasible is it to enable multi-dimensional filtering? e.g. Formats=Video & Packages=Xarray

I think this capability will become more important as the gallery grows.

**Comment by clyne** [comment]
That sounds like great news! Thanks for clarifying.
