### ISSUE TITLE
Add support for hosting video tutorials and associated notebooks created by Xdev

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#146]
This issue is discussed in a forum question on the Foundations site [here](https://github.com/ProjectPythia/pythia-foundations/discussions/118).

**Comment by clyne** [comment]
Assigning Julia just to make this official :-)

**Comment by jukent** [comment]
See our new repository https://github.com/ProjectPythia/pythia-tutorials !!

**Comment by brian-rose** [comment]
To be discussed at Ad hoc tutorial content meeting on 11/15
