### ISSUE TITLE
Automated build for PRs?

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#16]
While #15 adds instructions for users to build the portal site locally, which is great for testing purposes, it would be even better to automate this.

Is there a github action or other mechanism we can use so that the rendered site is built automatically for every open pull request? E.g. anyone can download a zip file of the rendered site and view locally in a browser?

**Comment by andersy005** [comment]
Now that #17 has been merged, any subsequent PR event will trigger a build on Readthedocs... Clicking on `details` takes the user to a preview link on Readthedocs:


![Screen Shot 2021-01-07 at 6 16 54 PM](https://user-images.githubusercontent.com/13301940/103962697-cfa7ab80-5114-11eb-9be9-28b6bbd1682b.png)

**Comment by brian-rose** [comment]
@andersy005 this is great! I just test-drove this over at #15 and it works great. This should accelerate our work of building out the  site.

**Comment by brian-rose** [comment]
I'll close this, since we now have a great working solution.
