### ISSUE TITLE
CONTRIBUTING.md references 'content' directory which no longer exists

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#161]
After merging #159 the CONTRIBUTING.md file is now out of sync with reality; it references the directory 'content' which has been renamed to 'folder'.

cc @jukent

**Comment by brian-rose** [comment]
Good catch @clyne. Actually the CONTRIBUTING.md was already wrong... the content moved over to the `portal` directory some time ago. But nobody noticed the discrepancy.

Just submitted a PR to fix this.

**Comment by jukent** [comment]
Oh thank you! That makes so much more sense now. I was just fixing the image path and missed that there were other updates that needed to be made.
