### ISSUE TITLE
make a conda-forge recipe for our pythia-datasets package

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#162]
Should sphinx be in our environment.yml file? I tried to build the site and was informed that my version of sphinx (v3.4.3) was out of date. I assumed running 

`conda env update -f ../ci/environment.yml`

would fix the problem, but no such luck. I had to explicitly update sphinx. If it is not practical to nail down all our dependencies in the .yml file than perhaps we should put a note in the contributors guide on how to deal with this situation.

**Comment by brian-rose** [comment]
Hmm this sounds like a question for @dopplershift. Personally I rarely update environments because it seems easier to treat them as disposable, just delete and recreate it with the latest versions. But I would have thought `conda env update` was the *correct* thing to do in this case.

I don't see any harm in adding sphinx explicitly to our list of dependencies, I just didn't think we needed to.

**Comment by dopplershift** [comment]
`conda env update` updates the environment for any package additions/removals in `environment.yml`. If you want to update the versions of the installed packages, this is a normal `conda update --all`.

**Comment by brian-rose** [comment]
Right! I frequently get confused about what the `env` modifier does to conda commands.

@clyne, maybe the best action here is to add a note about `conda update --all` in one or more places in our guides? And perhaps also to the list of [Useful Conda commands](https://foundations.projectpythia.org/foundations/conda.html#useful-conda-commands) in our brief Foundations section.

**Comment by clyne** [comment]
I think that makes sense and can make that change. Thanks

**Comment by brian-rose** [comment]
I've just encountered another stumbling block.

Doing `conda update --all` does NOT update packages that have been installed by pip. This just came up for me in our Foundations repo, where we use pip to install `pythia-datasets`. Running `conda update --all` did not pick up the recent new release of our datasets package, which caused a runtime failure.

I had to do `pip install pythia-datasets --upgrade` after running the conda update.

Maybe this is best raised in a separate issue on the Foundations repo, but just noting here that `conda update --all` doesn't always actually update all.

**Comment by dopplershift** [comment]
This is why I avoid using `pip` in conda environments like the plague...er....yeah. `conda` updates all the packages it knows about. It doesn't know about the things you install using `pip`--you need to use `pip` to manage those.

The solution IMO is to make a conda-forge recipe for our pythia-datasets package.

**Comment by clyne** [comment]
Would having a conda-forge recipe allow us to get away from using pip? If so, +1!

**Comment by brian-rose** [comment]
Yes, exactly. 

For a simple package like this the recipe should be trivial.

**Comment by clyne** [comment]
Sounds good. I relabeled the issue. Also, just a reminder in this note to update guides as appropriate with this information.

**Comment by mgrover1** [comment]
@brian-rose are you planning on adding pythia-datasets to conda-forge then? Otherwise, I can take care of it!

**Comment by brian-rose** [comment]
> @brian-rose are you planning on adding pythia-datasets to conda-forge then? Otherwise, I can take care of it!

I'm on it. Actually the PR is all ready to go, I just asked you via email if you are willing to be listed as one of the maintainers!

**Comment by brian-rose** [comment]
The PR for the recipe on conda-forge is here: https://github.com/conda-forge/staged-recipes/pull/16222

**Comment by brian-rose** [comment]
We now have a conda-forge package for pythia-datasets and no longer using pip. 

Leaving this issue open for now until we update the docs with best practices for keeping users' conda environments up to date.

**Comment by brian-rose** [comment]
The two PRs referenced above finish updating our various guides. @clyne you didn't get tagged for review on either PR, but you're welcome to take a look.
