### ISSUE TITLE
PR template that reminds users how to open in draft to avoid triggering premature review requests

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#184]
Update the Contributor's Guide (here and in Foundations?) to reflect new policies from today's IWG meeting:

Start all PRs as draft PRs
@-mention people to get “Please take a look at this work in progress” for draft PRs (don't request review)
Don’t convert PRs to “regular” status until build/tests pass

**Comment by brian-rose** [comment]
In addition to @-mentioning individuals, I suggest also including the possibility of @-mentioning teams. I realize that creates additional notifications for a lot of individuals, but there are lots of times when a PR author may prefer not to single out individual people for help, or just not know who is most appropriate to tag.

**Comment by clyne** [comment]
New plan: rather than updating contributor's guide we should simply provide a PR template that provides information on draft vs regular PR

**Comment by brian-rose** [comment]
> New plan: rather than updating contributor's guide we should simply provide a PR template that provides information on draft vs regular PR

Yes, and also reminds the user opening the PR that review requests are generated automatically when a regular (non-draft) PR is opened.

**Comment by brian-rose** [comment]
We'll need some help from someone on the @ProjectPythia/infrastructure team who is knowledgeable about PR templates.

**Comment by dopplershift** [comment]
The most basic would be to add `pull_request_template.md` (which is just a markdown file) to the [.github](https://github.com/ProjectPythia/.github).

You can have multiple templates, but there's no web UI to access them, they're controlled by passing a parameter in the URL. So if we wanted special templates for e.g. "edit this page" from the docs.
