### ISSUE TITLE
[Security] Workflow linting.yaml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by Freakston** [ProjectPythia/projectpythia.github.io#195]
The workflow linting.yaml is referencing action pre-commit/action using references v2.0.3. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by kmpaul** [comment]
Hey, @ProjectPythia/infrastructure:  We are using pre-commit-ci, so why do we still have the `linting.yml` workflow at all?  Can we just delete this?

**Comment by dopplershift** [comment]
Yeah, looks like `linting.yml` can just be removed since PRs are getting checked by the pre-commit service.

**Comment by kmpaul** [comment]
Closed with #201 and ProjectPythia/pythia-foundations#203
