### ISSUE TITLE
Collect Pythia presentations in one place

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/projectpythia.github.io#206]
Today's @ProjectPythia/education meeting, a desire was expressed to collect the variety of Pythia-related posters, presentations, etc. in one place. We could present this in the gallery, or potentially have a separate section or book dedicated to collecting these materials, or even future community materials that choose to reference us.

**Comment by brian-rose** [comment]
I was thinking about this while working on #215. Since way back, we've had a link to the 2021 AMS Pythia presentation on our [About page](https://projectpythia.org/about.html#ams-2021-project-pythia-presentation), but that's pretty out of date now.

I think a little gallery hosted somewhere on projectpythia.org would be great.

**Comment by mgrover1** [comment]
Here is a list from the Outreach Working group

- AGU - 3 Posters/Talks
   - Kevin P
      - [Pangeo and Project Pythia Helping Geoscientists Navigate the Scientific Python Ecosystem](https://agu2021fallmeeting-agu.ipostersessions.com/Default.aspx?s=CF-91-F4-F8-35-E4-B7-40-F2-8C-F6-86-76-97-11-02)
      - [Project Pythia: A Resource to Help Geoscientists Navigate the Scientific Python Ecosystem](https://agu2021fallmeeting-agu.ipostersessions.com/Default.aspx?s=25-22-8E-6D-6E-CB-B4-E9-6D-08-78-2A-61-2F-62-09)
   - Julia
       - [ESDS Educational Efforts](https://t.co/hQ1wGQZB18)
- AMS - 3 Talks
   - Drew ([slides](https://docs.google.com/presentation/d/1NuV5sI3oGhvuUt_s8hzmj0UA9MqCtlxWTADbJHjr9ow/edit?usp=sharing))
   - Kevin T ([slide deck](https://docs.google.com/presentation/d/1D8kkpsX4CE3rT5QQliH6JfKYeY76fT1gClIEzboxgko/edit#slide=id.p))
   - Max ([slides](https://docs.google.com/presentation/d/1aTw0DmaZ-7PQtWXxQqdik825r5mOoYRe/edit?usp=sharing&ouid=113419461755911727326&rtpof=true&sd=true))

**Comment by brian-rose** [comment]
Thanks @mgrover1 !
I will go ahead and incorporate these links into the revised About page in #215

**Comment by brian-rose** [comment]
Can we close this since #215 added a table of Pythia presentations to the [About page](https://projectpythia.org/about.html)?

**Comment by dcamron** [comment]
@brian-rose Sounds good to me. Thanks for including that there!
