### ISSUE TITLE
Collect and display usage metrics on portal

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#207]
From the Pythia proposal: 

_The number of visitors to the site will be tracked over time and will provide a strong indication of the number of users and how that count changes over time. Making this information public, **by displaying it on the web site**, will help instill confidence in the resource and further attract other users. At a finer granularity we will track page hits and downloads for specific training material (tutorials, example scripts, Jupyter Notebooks, etc.) so that we can answer questions such as: how useful is our introductory Python material, how many people are interested in scalability, or specific domain functionality? These content metrics, which we will begin collecting as soon as the portal is first deployed  will help inform future development._

**Comment by jukent** [comment]
Can you post any relevant links to the usage statistics here?

**Comment by clyne** [comment]
Duplicate of #319. Closing
