### ISSUE TITLE
Mention our connection with the Pangeo community

### ISSUE THREAD

**Issue by andersy005** [ProjectPythia/projectpythia.github.io#214]
Currently, there's no mention of **Pangeo** anywhere on our landing page. The same applies to our [foundations book](https://foundations.projectpythia.org/search.html?q=pangeo). During the early stages of Pythia, [Pythia was branded as the new, main education initiative within the Pangeo Community](https://medium.com/pangeo/pangeo-2-0-2bedf099582d). I think it would be valuable to provide clarity about our connection with the Pangeo community. 

P.S. 

This topic came up during the Pangeo steering council meeting.

**Comment by kmpaul** [comment]
See https://github.com/pangeo-data/pangeo/issues/866, too.

**Comment by brian-rose** [comment]
We can address this with a long-overdue revision to our landing page as called for in #116.

I'll try to get a PR submitted shortly.

**Comment by brian-rose** [comment]
#215 takes case of this on the main Pythia landing page. 

I think it would be good to add some similar text / link to the Foundations title page.

**Comment by kmpaul** [comment]
Yeah.  With pythia-foundations#243, I think we can close this.
