### ISSUE TITLE
Highlighting all of the Pythia resources from the landing page

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#222]
Thanks to @brian-rose et al we now have an awesome new landing page for Project Pythia. Our landing page states that we have "two main resources" for learning. I think we have more, and it is time to highlight them and make them accessible from our main page. We have some tremendous additional resources, that our community could really benefit from, but they are not _easily_ found. In particular:

1. **The Xdev-organized "Python Tutorials"**: The recordings of these webinars and their associated repos can be used over and over again. The material is currently collated [here](https://ncar-xdev.github.io/status/tutorials.html), and can be found from our Resource Gallery, but only if you plug in the right filters. Let's have a write-up on the landing page that with one click directs people to the recordings, the repos (currently here: https://github.com/ProjectPythiaTutorials, not under the https://github.com/ProjectPythia umbrella), AND possibly the calendar for future events). Is there a reason not to open these well-attended tutorials to the outside world? Note, there is an existing issue discussing this topic already: #157 
2. **pythia-datasets**: Currently this is a GitHub [repo](https://github.com/ProjectPythia/pythia-datasets), but in the future could expand to support larger data sets than can't be stored on GitHub. Publicly accessible, geoscience data that are appropriate for experimenting with different tools and techniques are not always easy to come by. These data sets have value outside of the training material that makes use of them. Why not highlight their existence as a Pythia resource?
3. **pythia-cookbook**: Coming soon, but definitely part of the collection of great resources offered by Pythia. Let's make sure that people visiting our landing page are aware of them!

**Comment by kmpaul** [comment]
Related to https://github.com/ProjectPythia/projectpythia.github.io/issues/157
