### ISSUE TITLE
Make it easier for the community to figure out how to communicate with us

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#267]
I think we might make it easier for the community to figure out how to communicate and get updates from us than we currently do. Currently, we have a "Community" entry on our main nav bar that takes you to "Join us" deep in our landing [page](https://projectpythia.org/#join-us). Under "join us" the user is presented with options for GitHub discussions, reading our contributors guide, joining us on github, and, reading our code of conduct. 

There are a couple of things about our current setup that I think are less than ideal and unhelpful to the user:

1. The presentation and choices are really more aimed at contributing that getting help
2. 1. I'm not sure "Community" conveys that this is where you go to communicate with us or get information.
3. I don't think these options under "join us" map very well into the things that users typically want to do when they visit a site like Pythia's. I'm guessing a lot of users trying to reach us want to: report a bug, ask a question, get informed about updates/events, and possibly get involved. 

Consider the "contact us" [page](https://www.fatiando.org/contact/) on Fatiando:

1. "contact us" is more descriptive than "community"
2. The page is stand alone, and uncluttered
4. There are clear options for the things that users typically want to do: chat, bugs&features, updates, and so on

There is some further discussion on this topic [here](https://github.com/ProjectPythia/projectpythia.github.io/discussions/260)

**Comment by jukent** [comment]
There has been some progress on this recently with the [Pangeo discourse page](https://discourse.pangeo.io/c/education/project-pythia/60)

Pinging the OWG team to move this forward @dcamron @mgrover1 @ktyle

**Comment by brian-rose** [comment]
@r-ford will update the portal and the GitHub org page

@dcamron will post pinned links to the discourse on our legacy discussion pages

**Comment by clyne** [comment]
Just adding a note there  is some further discussion on this topic [here](https://github.com/ProjectPythia/projectpythia.github.io/discussions/260)
