### ISSUE TITLE
Add link to AMS 2021 presentation

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#29]
The recorded AMS presentation gives an overview of Project Pythia and should probably be accessible from the web site (not as educational content, but something for the "about project pythia"). This begs the question of where videos should live. Should we simply upload to youtube? Would it make sense to have a "Project Pythia" channel on YouTube? Is this more fodder for our contributors guide. The link to the AMS talk is here:

https://drive.google.com/file/d/1JfBDF978grhcdIKcRgpPUYD84tX2R9OL/view?usp=sharing

**Comment by jukent** [comment]
I believe this is a repeated issues with #27 and #28

**Comment by clyne** [comment]
It is indeed. I was getting errors from GitHub. I will close the duplicates.
