### ISSUE TITLE
Google calendar not displaying

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#290]
Currently on our portal page at https://projectpythia.org/#meeting-event-calendar, where the meeting calendar should be displayed, I'm just seeing "I'm not a robot" .

**Comment by dcamron** [comment]
I'm not getting this behavior with my computer/browsers/ISP at home.

**Comment by brian-rose** [comment]
Now I'm not seeing it either, same location / ISP but different machine. Strange. I'll check it again tomorrow.

**Comment by brian-rose** [comment]
Whatever it was seems to have resolved itself. Closing this.
