### ISSUE TITLE
ORG: migrate from ProjectPythiaCookbooks

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/projectpythia.github.io#295]
Capturing project progress on the migration of content and infrastructure from @ProjectPythiaTutorials to @ProjectPythia. Please comment here or edit this post as completed.

## Repos
| Repo | Assignee | Moved | Infrastructure updated | Authors migrated |
| --- | --- | --- | --- | --- |
| cookbook-actions | @brian-rose | Y | Y | |
| HRRR-AWS | @ktyle | Y | Y | 
| cmip6 | @r-ford | Y | Y |
| template | @jukent | Y | Y |
| radar | @mgrover1 | Y | Y |
| gridding | @dcamron | Y | ProjectPythia/gridding-cookbook#8 | Y |
| packaging | @dopplershift | Y | Y | N/A |
| physical-oceanography | @mgrover1  | Y | Y |
| intake |@dopplershift | Y | Y | 
| test (contributor's guide) |N/A |N | |
| cesm-lens-aws |  | Y | Y |
| mpl-colorbar | N/A | N | |
| xgcm | | Y | |
| projectpythiacookbooks.github.io | @jukent | Y | Y |
| .github/CONTRIBUTING.md | @jukent | Y  | Y |
| projectpythia.github.io/portal/CONTRIBUTING.md | @jukent | Y  | Y |

**Comment by brian-rose** [comment]
Template updated in https://github.com/ProjectPythia/cookbook-template/pull/99

**Comment by jukent** [comment]
Cookbook Contributor's guide updated in https://github.com/ProjectPythia/.github/pull/35

**Comment by brian-rose** [comment]
Packaging Cookbook updated in https://github.com/ProjectPythia/packaging-cookbook/pull/22

**Comment by jukent** [comment]
Gallery updated in https://github.com/ProjectPythia/projectpythiacookbooks.github.io/pull/99

**Comment by mgrover1** [comment]
Radar Cookbook updated in https://github.com/ProjectPythia/radar-cookbook/pull/83

**Comment by brian-rose** [comment]
CESM-LENS cookbook updated in https://github.com/ProjectPythia/cesm-lens-aws-cookbook/pull/10

**Comment by dopplershift** [comment]
Intake cookbook updated in: https://github.com/ProjectPythia/intake-cookbook/pull/24

**Comment by mgrover1** [comment]
Physical Oceanography updated in: https://github.com/ProjectPythia/physical-oceanography-cookbook/pull/34

**Comment by ktyle** [comment]
HRRR-AWS cookbook updated in https://github.com/ProjectPythia/HRRR-AWS-cookbook/pull/18

**Comment by jukent** [comment]
Updating main contributor's guide: https://github.com/ProjectPythia/projectpythia.github.io/pull/296

**Comment by dcamron** [comment]
Closing as completed!
