### ISSUE TITLE
Initial Content & Topics

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#3]
We need to "quickly" move on deciding what *initial* content should go on the site.  Obviously, links to external Jupyter Notebooks is one type of thing we want to gather, but that's not the only form of content to consider.  We should consider external websites hosting tutorials, videos, etc.  **What kinds/formats of material do we hope to present on the Pythia Portal?**

Another important thing to consider in terms of organizing that content is **what *topics* do we want to cover on the portal.**  That is, how do we want to organize the content?

**Comment by jukent** [comment]
Per a discussion yesterday with @kmpaul -- a priority before adding new content is to make sure all the content from the [old repo] (https://github.com/NCAR/ProjectPythia) is included. I am creating a [Google Spreadsheet ](https://docs.google.com/spreadsheets/d/1QqNedI7eJdfX1KIZ410EW_eOpq7bmPjI-0tOHeWLm3M/edit?usp=sharing) that everyone who attended Wednesday's meeting is invited to edit. This seemed the easiest way to me to keep track of which files have been accounted for. Let me know if you have a different method you prefer!

**Comment by jukent** [comment]
I picture the gallery being able to display content of all formats (notebooks, videos, static pages, etc) and for a gallery specific search or refinement feature where the results are also displayed in the format of the gallery (currently they display as a list). The search feature could have a search bar but also drop down menus for format (say you only want to display notebooks) or for topics. We would need to add tagging functionality to make these searches work best.

**Comment by dcamron** [comment]
Regarding Unidata's python materials, we primarily have scattered collections of examples/tutorials for our specific projects ([MetPy](https://unidata.github.io/MetPy/latest/), [Siphon](https://unidata.github.io/siphon/latest/), and [python-awips](http://unidata.github.io/python-awips/)) as well as our own static [Python training site](https://unidata.github.io/python-training/). python-training ([repo](https://github.com/Unidata/python-training)) primarily hosts:

* A brief narrated "Intro to Python" guide roughly tailored for beginner students in the geosciences, with some helpful external links
* Our gallery of notebook examples, mostly meteorological product or task based notebooks. These vary in complexity
* Guided workshop content notebooks, from which we have built our in-person university and conference python workshops. About 50% of these are tool-based (e.g. Numpy, pandas, xarray), and 50% topic-based intermediate+ notebooks which are built to guide through meteorological product generation or domain-specific exercises. Some of these have defined interactive portions where an external python script with a solution to an in-notebook problem is magic loaded.
* Some loose "how can I use this on my own computer" content to tie it together

Currently python-training is not being built and deployed and loved. I will be dedicating some time to revamping its infrastructure first thing in 2021, and we will continue to build it and keep it around for now. Our JupyterHub instances also pull down this repo for users to have direct access to (future opportunity for Pythia content?).

We also host weekly produced [MetPy Monday](https://www.youtube.com/playlist?list=PLQut5OXpV-0ir4IdllSt1iEZKTwFBa7kO) narrated demonstrative videos on YouTube. There are over 150 of these and they vary vastly from "how do I install Python" to advanced python syntax to scripting widgets in Jupyter to meteorological data access and much more.

We should be more than able and willing to commit much of that content directly to Pythia, though I'm not sure yet what all design changes should be made. The easiest place to start would probably be our various gallery and project-specific example materials.

@dopplershift can comment if I've left any content out or with any extra considerations here.
@srcarter3 designs and curates the python-awips content.
@julienchastang leads our existing [Science Gateway](https://science-gateway.unidata.ucar.edu/) (python-training and more available on JupyterHub+Jetstream) efforts.

---
To summarize explicitly in a list of what's available, to be checked as evaluated/committed:
 - [ ] MetPy [examples](https://unidata.github.io/MetPy/latest/examples/index.html) and [tutorials](https://unidata.github.io/MetPy/latest/tutorials/index.html)
 - [ ] Siphon data access [examples](https://unidata.github.io/siphon/latest/examples/index.html)
 - [ ] Python-awips [examples](http://unidata.github.io/python-awips/examples/index.html)
 - [ ] python-training [gallery](https://unidata.github.io/python-training/gallery/gallery-home/)
 - [ ] python-training [intro materials](https://unidata.github.io/python-training/python/intro-to-python/)
 - [ ] python-training [workshop materials](https://unidata.github.io/python-training/workshop/workshop-intro/)
 - [ ] [MetPy Mondays](https://www.youtube.com/playlist?list=PLQut5OXpV-0ir4IdllSt1iEZKTwFBa7kO) video series

**Comment by kmpaul** [comment]
Thanks, @dcamron!  I'll add the Xdev Tutorials to the list, too:

- [ ] [Xdev Python Tutorials](https://ncar.github.io/python-tutorial/)

**Comment by clyne** [comment]
- [ ] [GeoCAT plotting gallery](https://geocat-examples.readthedocs.io/en/latest/)
- [ ] [wrf-python plotting gallery](https://wrf-python.readthedocs.io/en/latest/plot.html)

**Comment by erogluorhan** [comment]
Thanks @clyne ! In addition to those plotting examples, we should also add to the list:

- [ ] Jupyter notebooks of AWS demonstrations of several GeoCAT-comp functions (i.e. work in collaboration with NCAR's Science at Scale)

**Comment by ktyle** [comment]
Hi everyone and happy 2021!

I thought it would be useful to make available the notebooks I developed for the class I debuted this past semester. Currently they sit in a private repository that I set up for the class, so I will need to send invites to Pythia team members in order to grant access. I will send them out to the PI's as well as everyone who is on this issue thread. If anyone else wants an invite, let me know!

As the semester went on, I gradually developed a bit of organizational and narrative flow to the notebooks. Still a lot more needs to be done, but it's worth having folks take a look at this point. They are all pre-run so you should be able to see the content that the notebooks produce.

What I'd like to do next is to make these notebooks site-agnostic; currently, most of the data files that are used in the notebooks reference NFS-directories on my department's servers.

The link to the Fall 2020 notebooks is [https://github.com/DAES433533/Fall2020](https://github.com/DAES433533/Fall2020) .

**Comment by clyne** [comment]
> Hi everyone and happy 2021!
> 
> I thought it would be useful to make available the notebooks I developed for the class I debuted this past semester. Currently they sit in a private repository that I set up for the class, so I will need to send invites to Pythia team members in order to grant access. I will send them out to the PI's as well as everyone who is on this issue thread. If anyone else wants an invite, let me know!
> 
> As the semester went on, I gradually developed a bit of organizational and narrative flow to the notebooks. Still a lot more needs to be done, but it's worth having folks take a look at this point. They are all pre-run so you should be able to see the content that the notebooks produce.
> 
> What I'd like to do next is to make these notebooks site-agnostic; currently, most of the data files that are used in the notebooks reference NFS-directories on my department's servers.
> 
> The link to the Fall 2020 notebooks is https://github.com/DAES433533/Fall2020 .

Thanks for including @ktyle. This raises a couple of issues in my mind:

1. This is a complete, semester-long course on a particular topic. When we think about how users might search for topics and how we might present them, one pull down menu option might be "on-line courses" like this one. Alternatively we could think about making individual notebooks available for specialized topics, or a combination of both. 
2. With regard to data: we've promised to make our data available on NCAR's public DASH repository. So that is one option. However, if this content is hosted externally and there is a better option for hosting the data, I don't see why needs to be hosted on DASH. What I'm getting at is we may have to come up with some policy/guidelines for when we need to put example data on DASH.

**Comment by clyne** [comment]
All, to help think about organizing this material I took a stab at creating a spreadsheet showing content type and material format. It may or may not be useful for discussion. Here it is:

https://docs.google.com/spreadsheets/d/1PtGLr8D9zFZ8Tlktgh4kRH1gz3C2-RUcSx6OX_Gajvc/edit#gid=0

**Comment by kmpaul** [comment]
With the initial content suggestions listed above now having been added to the `pages/links.md` page (#20), should we close this issue and create new issues for suggestions on how to improve it?

**Comment by ktyle** [comment]
That sounds good to me. I am presently putting together a (fairly large) list of the links I've collected over the last few months, in between attending AMS virtual sessions.

**Comment by kmpaul** [comment]
Great!  Do you want to try to add them as a separate PR, then?

**Comment by ktyle** [comment]
Sure ... I'll go ahead and close this issue and then will open a PR once I work in a portion of my links.
