### ISSUE TITLE
New URL: projectpythia.org

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#30]
I have purchased the domain name **projectpythia.org** and DNS finally updated to point it to the portal.  It should automatically enforce HTTPS, so you should get a secure connection to the portal.

Please let me know if you have any problems using the new URL:

https://projectpythia.org

If you have problems, indicate them in this issue.

**Comment by clyne** [comment]
Nice! I assume we should now start advertising the new URL publicly?

**Comment by jukent** [comment]
How long should we leave this issue open?

**Comment by clyne** [comment]
Are their places on our site where we need to update the URL?

**Comment by jukent** [comment]
Good point! I will look through for that.

**Comment by jukent** [comment]
I'm getting a 404 when I click the projectpythia.org link in the about section. @kmpaul

**Comment by kmpaul** [comment]
I am not.  Try again?

**Comment by kmpaul** [comment]
Wait.  I am now.  Hold on.  I'll try to diagnose.

**Comment by kmpaul** [comment]
It looks like the URL is being properly forwarded to GitHub pages...but it's acting like the page is not deployed.

**Comment by kmpaul** [comment]
Ok.  It looks like it is back.  The settings on the repository got changed and it no longer was pointing to *projectpythia.org*.  I set that some time ago, and I didn't change it.  But I've set it back.  (This will be mildly annoying if GitHub keeps forgetting the domain.)

**Comment by jukent** [comment]
It's back for me too. I hope GitHub doesn't forget again.

**Comment by andersy005** [comment]
>  The settings on the repository got changed and it no longer was pointing to projectpythia.org. I set that some time ago, and I didn't change it. But I've set it back. (This will be mildly annoying if GitHub keeps forgetting the domain.)

Adding `cname` field to the deploy GitHub action should fix this problem:

https://github.com/ProjectPythia/projectpythia.github.io/blob/8aacc4b7c79bf974229c5e11378a45a80d935da3/.github/workflows/ci.yaml#L32

E.g.:

```yaml
publish_dir: ./content/_build/html 
cname: projectpythia.org
```

**Comment by kmpaul** [comment]
Wait.  @andersy005:  Are you saying that the GitHub action is "erasing" this field every time it runs?  Is that correct behavior?

**Comment by andersy005** [comment]
> Are you saying that the GitHub action is "erasing" this field every time it runs? 

It's my understanding that the existing CNAME file was manually added to the gh-pages. During the deployment stage, the GitHub action creates a new branch for every new build/deployment. As a result, The CNAME file needs to be committed to the (new/custom) branch the GitHub action deploys from.  Does this answer your question? :)

**Comment by kmpaul** [comment]
Yep.  Thanks.  I'll make the change.

**Comment by kmpaul** [comment]
This is done, now.

**Comment by kmpaul** [comment]
Should this be closed, now?  Or is there anything else that needs to be addressed (pun intended)?

**Comment by jukent** [comment]
I think we can close it, and open a new issue if any new problems related to this arise.
