### ISSUE TITLE
Guidance on how to cite Pythia

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#306]
We need to figure out how we want folks to cite Project Pythia **and** provide guidance on this to the community. One possibility is to simply cite the main landing page for everything. A bibtex entry might look like:

  @misc{project_pythia,
    author = "{Project Pythia contributors}",
    title = "Project Pythia",
    year = "2021",
    url = "https://projectpythia.org/",
    note = "[Online; accessed 18-January-2023]"
  }

with the "note" updated with the date of access. This is basically what wikipedia does.

**Comment by ThomasMGeo** [comment]
A Zenodo DOI/ citation.cff would also be great!

**Comment by brian-rose** [comment]
Related: citation of Foundations book https://github.com/ProjectPythia/pythia-foundations/issues/309

**Comment by brian-rose** [comment]
We need to address this (including the citation of individual cookbooks) prior to our summer 2023 hackathon.

**Comment by r-ford** [comment]
Related issue on cookbook-gallery repo: https://github.com/ProjectPythia/cookbook-gallery/issues/15

**Comment by brian-rose** [comment]
We decided to use Zenodo to mint DOIs for Foundation releases and use those DOIs as the citation format. So this is waiting on https://github.com/ProjectPythia/pythia-foundations/issues/344.

Once the DOI is in place, we will need to update the text in Foundations to make it obvious how to cite.

**Comment by jukent** [comment]
DOI citation PR for foundations: https://github.com/ProjectPythia/pythia-foundations/pull/388

**Comment by brian-rose** [comment]
At today's IWG meeting we briefly discussed the question of "how to cite Pythia as a project" rather than citing individual works. Citation methods for Foundations and individual Cookbooks have been taken care of, but there is still scope for providing a "go-to" citation for the project as a whole.

We landed on the idea of putting the text of our NSF proposals into citable archives (Figshare? Zenodo?) with author attribution.

Once that is done and DOIs are generated, then we just need to add some guidance on our main project web page.

**Comment by brian-rose** [comment]
The text of the new NSF GEO OSE proposal is now here:
https://doi.org/10.5281/zenodo.8184298

**Comment by jukent** [comment]
Great so now the remaining task is to point to this in a "how to cite" page on the main portal, and then on each subpage (say foundations or a cookbook) that has a "how-to-cite" page with information on citing that specific piece, we add a paragraph on how to cite the entire project. I'm understanding that correctly?

**Comment by brian-rose** [comment]
I think including that info in every cookbook may be overkill. A prominent "how to cite" instruction on the main project home page should be enough, especially since there's a prominent link back to the project home page at the top of every cookbook nav bar already.
