### ISSUE TITLE
Cookie Cutter template

### ISSUE THREAD

**Issue by WesleyTheGeolien** [ProjectPythia/projectpythia.github.io#32]
Hello,

I was looking around for a good notebook gallery template and stumbled across your site (pangeo talk pointed me there).

I ripped out most of the code to build a Cookiecutter template that builds your notebook gallery. The current repo is here: https://github.com/WesleyTheGeolien/jupyter_notebook_sphinx_gallery

I would however be more than happy to transfer ownership to `ProjectPythia` if this is something useful to you and the greater community.

**Comment by jukent** [comment]
Thanks @WesleyTheGeolien. 

Team any thoughts on this? @andersy005 I believe you build most of the codebase in question(?).
