### ISSUE TITLE
Clarify instructions for joining Zoom meetings

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#323]
The Albany zoom account we are currently using to run our open meetings requires all participants to be logged into verified Zoom accounts. This is a university requirement that we cannot control.

There is currently no information about this requirement on [our meeting page](https://projectpythia.org/#weekly-working-group-meetings) or our [google calendar](https://calendar.google.com/calendar/u/0/r/settings/calendar/Y180cXB2ZjMxNmFmZDltdjBjaTdkMnVpYWZvZ0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

This has caused at least one invited guest to miss a meeting, see [this discourse post](https://discourse.pangeo.io/t/making-cookbooks-citable-best-practices/3170/10)

**Comment by dcamron** [comment]
With the change to UCAR Zoom, verified logins should not be required. Is the passcode in the calendar event and meeting notes enough from here? We can still add a small blurb to the portal section itself.

**Comment by r-ford** [comment]
Since we switched back to the UCAR Zoom, is this issue resolved?

**Comment by brian-rose** [comment]
We haven't heard of many people missing meetings because they can't find the right Zoom meeting lately, so I will close this.
