### ISSUE TITLE
Issue with dataset

### ISSUE THREAD

**Issue by rashmikulranjan** [ProjectPythia/projectpythia.github.io#334]
Do the CESM2_sst_data.nc and CESM2_grid_variables.nc in https://github.com/ProjectPythia/pythia-datasets/tree/main/data need to be updated. The format for date and time seem to have an issue

**Comment by brian-rose** [comment]
Hi @rashmikulranjan, could you clarify the issue you are running into?

It would help to see some example code to reproduce your issue if possible.

**Comment by r-ford** [comment]
Those datasets are used in the [Computations and Masks with Xarray](https://foundations.projectpythia.org/core/xarray/computation-masking.html) notebook. There are some time series plots in the ["Compute anomaly" section](https://foundations.projectpythia.org/core/xarray/computation-masking.html#compute-anomaly), and I don't see any issues with the datetime format there. I'll close this for now, but feel free to reopen the issue if you have any questions!
