### ISSUE TITLE
Add Pythia presentations to about.md

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#348]
https://github.com/ProjectPythia/projectpythia.github.io/blob/main/portal/about.md

The about page is hidden in the footer of the portal and is missing all 2023 and late 2022 talks.

**Comment by jukent** [comment]
Please comment here any presentations SINCE AMS 2022. So we need some SciPy 2022 and 2023, AGU 2022, and AMS 2023 links. Plus any other conferences I'm missing. (I know I did ISS 2023).

**Comment by jukent** [comment]
AGU 2022 [A Pangeo Community Tool for Open-Source Education](https://docs.google.com/presentation/d/19oWV7LULijtIYObrNW3ccoRLNFV9lYA0APuPlXAx_z8/edit?usp=sharing)

ESDS forum [Project Pythia: A Community Learning Resource for Geoscientists] (https://docs.google.com/presentation/d/1NGLFwqJdsu53CtsCqZLO3dxQtRcelOsm/edit?usp=sharing&ouid=107342162699810699865&rtpof=true&sd=true)

ISS 2023 [How Project Pythia Leverages GitHub for Community Contributions](https://docs.google.com/presentation/d/13MH5968BAfR6IxplGVbM2bSJ6uRoa5Wkzk5axqvmCX4/edit?usp=sharing)

Found this document -- https://docs.google.com/document/d/1ZmVs9pF6JLmgVbUDVh2K61pPpGBxCIuRjV0ar70yUBs/edit

**Comment by dcamron** [comment]
@ktyle we need SciPy last year, I can grab this year's. Are published Google Drive links the preferred links? Or should we find a new place to store talks?

**Comment by ktyle** [comment]
Last year's SciPy is in the "talks" folder in the Pythia shared drive: https://drive.google.com/drive/folders/1rSt5SEUcpnMygoC5b03Ka0FmeOUUPTlx 

I don't think the shared drive is open to all, though?

**Comment by brian-rose** [comment]
@dcamron and @brian-rose  and @mgrover1 all have some to add to this list.

**Comment by brian-rose** [comment]
Also the Ocean Sciences talk I gave this week!

**Comment by jukent** [comment]
We're missing an AMS talk from @dcamron and @ktyle. Great conference season!

**Comment by brian-rose** [comment]
I think with #406 merged we can close this now. Have we left anything out???

**Comment by jukent** [comment]
Maybe this can be an item on the agenda of all quarterly meetings? Just a quick check on what talks were given recently -- or this can be the job of the OWG.
