### ISSUE TITLE
Create Project Pythia Youtube Channel

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#35]
Per discussions in #27 and #33 we should create a Youtube channel specifically for Project Pythia videos.

[Here](https://support.google.com/youtube/answer/9481328?hl=en) are the suggested instructions for having multiple admins of the account if we want that.

**Comment by clyne** [comment]
As I recall NCAR/UCAR may have some kind of "corporate" account that we may want to piggy back off of. I'm checking and will report back.

**Comment by clyne** [comment]
@dopplershift , @dcamron you all have set up a YouTube channel for MetPy Mondays. Is there anything we know, or just follow the instructions linked above? Thanks.

**Comment by clyne** [comment]
> Per discussions in #27 and #33 we should create a Youtube channel specifically for Project Pythia videos.
> 
> [Here](https://support.google.com/youtube/answer/9481328?hl=en) are the suggested instructions for having multiple admins of the account if we want that.

I would think we might want a "brand" account,  not a regular one:

https://support.google.com/youtube/answer/9367690?hl=en

**Comment by dopplershift** [comment]
We just use Unidata's standard YouTube account for posting the MetPy Mondays. I have no idea if we're maximizing how things could be set up on YouTube.

**Comment by clyne** [comment]
OK. I've made several failed attempts to create a "brand" account. I think I'm having trouble because I have an existing brand account for another project. @jukent could you give it a try? I think once the account is created you can add other members with different roles. Thanks!

**Comment by jukent** [comment]
> OK. I've made several failed attempts to create a "brand" account. I think I'm having trouble because I have an existing brand account for another project. @jukent could you give it a try? I think once the account is created you can add other members with different roles. Thanks!

I have a meeting right now but will try after.

**Comment by jukent** [comment]
I created a Brand account called ProjectPythia. 

I am uploading the AMS presentation now.

**Comment by brian-rose** [comment]
I think the title and description are fine!

**Comment by jukent** [comment]
https://youtu.be/_UxlrwB_evo

Here is the link to the Youtube video! 
We will add more people to the brand account -- let's discuss this (and who wants to be added) during our next infrastructure meeting.

**Comment by ktyle** [comment]
Looks great!

**Comment by clyne** [comment]
Awesome! I have no guidance on comments. You might see what's been done for the "MetPy Monday" videos (or ask @dcamron). We do not have a circular, but I'm sure you could make one :-)

**Comment by dopplershift** [comment]
Looks good! We do have comments enabled, though that means of course some people try to use that as a support channel so we have in the descriptions:

> Unidata does not offer support via YouTube comments, please submit support tickets here: https://www.unidata.ucar.edu/support/

**Comment by jukent** [comment]
> Unidata does not offer support via YouTube comments, please submit support tickets here: https://www.unidata.ucar.edu/support/

I will add that! But with our Github discussions link.
