### ISSUE TITLE
Update NCAR and Unidata logos to be in compliance with new NSF guidance

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#371]
The landing page, and any other page that contains NCAR or Unidata logos or mentions NCAR or Unidata, will need to be updated per NSF's new branding [guidance](https://sundog.ucar.edu/page/7480).

**Comment by dcamron** [comment]
We should consider these in presentations, hackathons, etc. moving forward as well.

Todos here:
- [ ] Update any NCAR and Unidata logos. I've attached Unidata's logos here and can provide a Drive link as well
- [ ] Any text references of "NCAR" and "Unidata" should be updated to "NSF NCAR" and "NSF Unidata"
- [ ] We may want to make our footer and NSF acknowledgments clearer, where we should explicitly reference the "U. S. National Science Foundation"

Unidata logos:
![NSF-Unidata_lockup_horizontal_2023](https://github.com/ProjectPythia/projectpythia.github.io/assets/24628426/cec065f4-3fca-48c5-958b-6aa62a1e21f6)

![NSF-Unidata_lockup_vertical_2023](https://github.com/ProjectPythia/projectpythia.github.io/assets/24628426/cafe30c4-eb02-4762-bcbb-92527ea793bf)

Example acknowledgment text:
> NSF Unidata is one of the University Corporation for Atmospheric Research (UCAR)'s Community Programs (UCP), and is funded primarily by the U. S. National Science Foundation (Grant AGS-1901712).
