### ISSUE TITLE
Contributor's Guide

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/projectpythia.github.io#4]
Write a Contributor's Guide that defines collaboration methods for the Pythia Portal.

- Either .md or .rst is fine

**Comment by kmpaul** [comment]
I created a first draft of the CODE OF CONDUCT here:

[CODEOFCONDUCT.md](./CODEOFCONDUCT.md)

**Comment by brian-rose** [comment]
The first draft of the Contributor's Guide currently links to the Code of Conduct directly in the github repo. Probably better to make the CoC visible from the portal site itself.

**Comment by kmpaul** [comment]
I just made some edits to the to site that:

1. place the Contributor's Guide in the root directory of the repository,
2. update the language of the CoC to be less UCAR specific,
3. add custom scripting in `conf.py` to copy the CG and the CoC to the `content/pages/` directory when the site is built,
4. added a nav link to the CoC on the portal site.

I'm *really* sorry, but I forgot to clone my fork and cloned the main repo, instead.  So, there was no PR to go with these changes, but you can see the site to see what was done.

**Comment by brian-rose** [comment]
Just noting here that the CoC still says
```
The date that it was adopted by this project was [Enter date adopted].
```
I'm not sure if we need to have some explicit vote on adopting the CoC?

**Comment by kmpaul** [comment]
I missed that.  I'll fix it in another PR.

**Comment by kmpaul** [comment]
...actually, I just added it to the open PR.

**Comment by kmpaul** [comment]
Done and merged.

**Comment by kmpaul** [comment]
However, I still think the Contributor's Guide needs more work. ...Should we close this issue for now and either re-open it when we want to improve the Contributor's Guide (or create another issue)?

**Comment by brian-rose** [comment]
Hmm... I don't actually see any change in the CoC ??

**Comment by kmpaul** [comment]
Yeah.  Sorry.  I forgot to push the change.  😄  I'm putting together another PR for some bugfixes.

**Comment by kmpaul** [comment]
I believe this is fixed now.

**Comment by clyne** [comment]
> However, I still think the Contributor's Guide needs more work. ...Should we close this issue for now and either re-open it when we want to improve the Contributor's Guide (or create another issue)?

I'd say either leave it open, or close and open a new ticket.

**Comment by erogluorhan** [comment]
I am fine with closing this one, and we could open a new ticket when it comes to actually populating the Contributor's Guide

**Comment by brian-rose** [comment]
Ok, I'll close this now, and open a new issue for discussion about the future of the Contributor's Guide.
