### ISSUE TITLE
Jupyter Learning Resources for the Pythia Portal

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#40]
I've created [this issue](https://github.com/pangeo-data/jupyter-earth/issues/38) on the Jupyter Meets the Earth project repository (in the Pangeo-Data organization) to discuss the best learning resources for Jupyter and what we can link to on the Pythia portal.  When we get some good links, or indications that new content needs to be created, I will post them here.

**Comment by dcamron** [comment]
x projectpythia/pythia-foundations#97

**Comment by brian-rose** [comment]
I suspect this one can be closed given the Jupyter content in Foundations.
