### ISSUE TITLE
Fix drop down menu in resource gallery

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#419]
New theme breaks dropdown menu in resource gallery, but fixing the other infrastructure hangups due to the theme were more important. I'll look into this next week.

**Comment by erogluorhan** [comment]
Will also be needed in the cookbook-gallery

**Comment by jukent** [comment]
Was focused on the theme update in Cookbooks the last two days. I'm not sure I'll be able to fix this tomorrow (I'll take a look and document if I find anything), so I'm un-assigning myself to signal that someone else should look at this while I'm on PTO and at the SEA conference.

**Comment by jukent** [comment]
Also noticing that the Cookbooks gallery starts with "=================" when we don't want that.

New [Sphinx drop down documentation](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html)
