### ISSUE TITLE
Unify Meeting Notes?

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#42]
Since the Pythia meetings are now public on Zoom, and we have agreed on a common meeting time, does it make sense to *join* the two working group notes documents?  We could simply alternate "who runs the meeting" (IWG or EWG chair ...or John Clyne for quarterly meetings), but we could still use the same notes document.

Thoughts?

**Comment by clyne** [comment]
I think as working group chairs for the bi-weekly meetings it's up to you and Brian to decide what works best for you.

**Comment by brian-rose** [comment]
I don't have strong preference but I guess I lean toward keeping them separate. I do a lot of scrolling back to previous WG meeting notes when setting the agenda.

**Comment by kmpaul** [comment]
@brian-rose Would you be interested in combining notes documents?  I'm happy to do the merge and update the relevant pages.

**Comment by kmpaul** [comment]
Oh. Sorry I didn't see your post @brian-rose

**Comment by brian-rose** [comment]
@kmpaul I'm just wondering what do we gain by doing so? Is it about making the meetings notes easier for people to find?

If there's case for combining in order to help build participation, then I'm fine with that.

**Comment by kmpaul** [comment]
Yeah. That's what I was thinking. I put together a PR to add the Pythia meetings to the Pangeo website, and I put both EWG and IWG together since the meeting times were the same. I thought it would be confusing for people to know which _notes_ document to open for each meeting. So, I thought it would make it easier for everyone if there was only 1 document. 

But I could divide the IWG and EWG descriptions up on the Pangeo page and clarify the text. Perhaps that's a better approach.

**Comment by kmpaul** [comment]
Might still be hard for people to know which WG the meeting will be focused on, though. They need to consult the calendar.

**Comment by kmpaul** [comment]
So, just to be clear, I will try to summarize why I created this issue.

From an outsider's perspective (e.g., someone who hears about Python from the Pangeo website), Pythia appears to have 1 weekly meeting time (Thursdays at 1PM Eastern).  It also appears to have 1 Zoom Meeting room (with the same recurring password).  However, it has 2 different Notes documents, which would (I think) seem confusing to someone new.  

Personally, I think reducing confusion helps people get over the "sure, I'll see what's up with this project" barrier.  I'm not sure how many people will actually have problems with this, but it was just a thought.  If we don't have a homogeneous opinion on the subject, then I'm happy to keep things as they are and close this issue.

**Comment by brian-rose** [comment]
Thanks @kmpaul for this clear explanation. I think you've convinced me! The potential gain (lowering barrier to new people getting involved) outweighs the very minor inconvenience to the working group chairs.

I vote that we go ahead and unify the notes.
