### ISSUE TITLE
Duplicates in the resource gallery

### ISSUE THREAD

**Issue by kafitzgerald** [ProjectPythia/projectpythia.github.io#432]
It looks like items are being duplicated in the [resource gallery](https://projectpythia.org/resource-gallery.html).  

![Screen Shot 2024-06-04 at 12 19 58 PM](https://github.com/ProjectPythia/projectpythia.github.io/assets/7872563/4d686d41-f8cd-447a-85d1-14375cc3a027)

**Comment by brian-rose** [comment]
Ahhh, this looks much like the bug we *just* fixed in the Cookbook gallery, https://github.com/ProjectPythia/cookbook-gallery/pull/204

**Comment by brian-rose** [comment]
I think we have some code for our gallery generation duplicated across the two repositories, which is not ideal.
