### ISSUE TITLE
Separate infrastructure from content in "External links" page

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#44]
As discussed in our IWG meeting today, a first step before doing more work on gathering/assessing content and developing more advanced portal features is the separation of infrastructure from content.  In this case, the content we are referring to are the external links on the "External Links" page.  Currently, the way they are displayed and organized on the portal is intrinsically tied to the originating markdown document itself (i.e., all links are explicitly embedded in the markdown document).

What we need to do is separate the content (i.e., the links) from the infrastructure (i.e., the markdown page).  To do this, I suggest that:

- [x] all of the external links from the "External Links" page be copied to a YAML document (e.g., `links.yml` or similar) in the `content/` directory of the repository,
- [x] structure the YAML document to include fields for tags, description, etc.,
- [x] add a section at the bottom of `content/conf.py` that constructs the `content/pages/links.md` page at build time from the content in the YAML file (possibly building a gallery),
- [x] delete the current `content/pages/links.md` file and add it to the `.gitignore` file.

Optionally, I would say that we could additionally do (maybe in a separate PR):

- [x] create separate markdown documents for different tags found in the YAML file,

Anything else?

**Comment by clyne** [comment]
Maybe take a stab at identifying an initial list of tags (keywords?)

**Comment by kmpaul** [comment]
This looks done with #69!
