### ISSUE TITLE
Clean up portal look and feel

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/projectpythia.github.io#45]
It is controversial, I realize, but let's discuss how we would like to "clean up" (or "update" or "make prettier") the Pythia Portal page.  I think we've all worked on making the content on the site "good for now," and maybe it's time to revisit the actual look and feel of the site itself.

If I were to start off, I might suggest making the "links" page/gallery the landing page and provide nav to other content.  

What else do we want to do?

**Comment by clyne** [comment]
Thanks for starting this thread @kmpaul. A few things that might help with usability/presentation IMHO:

1. Remove the download and full screen icons. The landing page is busy enough, and I don't think these are useful.
2. The main menu is on the left column, but when click on one of the items you get what is essential a sub-menu that appears in the *right*  column. The menu selector and sub-menu selector are completely disconnected.
3. I'd move the paragraph of text that appears on the landing page to the "About" section, replacing it with a catchy tag line such as "Learning Python for Geoscience" and adding a nice graphic. FYI I've reached out  to UCAR's graphic designer to see if she can help.
4. I'm not sure I agree with making the links gallery the landing page. Too busy. But maybe having a few featured links/resources on the landing page would be nice.

**Comment by kmpaul** [comment]
Ok, I've looked into this a bit.

Regarding 1:  There is an existing pull request to make the "full screen mode" button optional (https://github.com/executablebooks/sphinx-book-theme/pull/280).  The download button can be easily removed with a `    "use_download_button": False,` option in the `conf.py` `html_theme_options` variable.

Regarding 2: There does not appear to be a way of disabling the right-side TOC.  This seems to be a critical element of the theme itself.  Personally, I like the right-side TOC, but I can understand feeling like it is cluttering.

Regarding 3: That's pretty easy to do, obviously, since it's just moving content from one markdown file to another.

Regarding 4:  I don't entirely disagree with this.  I think it is most useful to put the feature people *want* (i.e., the reason most people would come to the site) directing in their face when they come to the site.  That reduces number of clicks or searching for "and now how do I get to the content".  For example, when you go to "google.com" you don't have to click a separate button to "search".  ...Although, *a gallery doesn't have to be the landing page.*  We *could* have something like a search bar right in the center of the landing page (maybe above a "browse content" button, for example, which *would* take you to a gallery).  ...But the search feature needs development (obviously).  So, in the mean time, we could have a "Browse Content" button on the landing page and a few "promoted items" in a tiny gallery.

**Comment by clyne** [comment]
The UCAR graphics designer, Simmi Sinha, has agreed to meet and give some  thoughts on dressing up the landing page. I will set up a meeting. @kmpaul, you or anyone else interested in attending?

**Comment by kmpaul** [comment]
Yeah.  I'm interested.  My calendar is up-to-date, albeit full.  😄

**Comment by kmpaul** [comment]
I have a working demo of the Sphinx Pythia Theme here:

https://sphinx-pythia-theme.readthedocs.io/en/latest/

All development on this should move to that repository.

**Comment by clyne** [comment]
@kmpaul this AGU [site](https://data.agu.org/) forwarded by @mgrover1 may be worth taking a look at for ideas. Supposedly it is hosted on GitHub

**Comment by mgrover1** [comment]
> @kmpaul this AGU [site](https://data.agu.org/) forwarded by @mgrover1 may be worth taking a look at for ideas. Supposedly it is hosted on GitHub

Here is the repo they used to make it https://github.com/AGU-Data/agu-data.github.io

**Comment by kmpaul** [comment]
Yeah.  It's a Jekyll-based site, so it would be a lift to convert it to a Sphinx theme.  But if people want to use that theme, I can try to do the work.  It'll take more time.

**Comment by kmpaul** [comment]
Is this satisfied or are there more issues we want to address about the look and feel of the portal?
