### ISSUE TITLE
publish-site Started to Fail recently due to build-book

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/projectpythia.github.io#457]
**What happened**:

The [publish-site](https://github.com/ProjectPythia/projectpythia.github.io/actions/workflows/publish-site.yaml) actions started to fail in the last two weeks. The error is happening at the [cookbook-actions/build-book.yaml](https://github.com/ProjectPythia/cookbook-actions/blob/main/.github/workflows/build-book.yaml)'s "Test for environment change" step, which uses `tj-actions/changed-files@v45`. 

The failure started to occur after the version bump from v44 to v45 for `tj-actions/changed-files`. FYI: @jukent 

The error message is:

"Error: Unable to locate the git repository in the given path: /home/runner/work/projectpythia.github.io/projectpythia.github.io.
   Please run actions/checkout before this action (Make sure the 'path' input is correct).
   If you intend to use Github's REST API note that only pull_request* events are supported. Current event is "schedule"."

With the `publish-site` actions, we don't run `Checkout the code from the repo` because `build_from_code_artifact: 'true'` in [here](https://github.com/ProjectPythia/projectpythia.github.io/blob/main/.github/workflows/publish-site.yaml).

**Minimal Complete Verifiable Example**:

https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10871645277

**Anything else we need to know?**:

It looks like we will need to either downgrade `tj-actions/changed-files` from v45 to v44 to fix things for now, or figure if we can run `actions/checkout` in `publish-site` as it is requested by v45.

**Comment by erogluorhan** [comment]
> My first guess is that a new path issue would be from some changes in the `changed-files` action, but I don't see anything promising in the [release notes](https://github.com/tj-actions/changed-files/releases) that would point to a change in how paths are handled.

![image](https://github.com/user-attachments/assets/cf96189a-c722-4931-ba60-86bd94e1e8c5)
They anounced a breaking change with v45.0.0 but I am not sure for now if it is directly related to our issue here.

> > or figure if we can run actions/checkout in publish-site as it is requested by v45.
> 
> @erogluorhan where do you see the user-facing differences for v45?
> 
> Changing to v44 seems like a safe way to have this working for now and to verify that this is the source of the error, but we don't want it to be pinned in an old version for however long.

Not sure about v45's user facing differences for now either. 

I also think we can try changing to v44 for a quick easy trial then can look into actual fix with v45

**Comment by jukent** [comment]
I didn't scroll down enough!

**Comment by erogluorhan** [comment]
Created a [PR](https://github.com/ProjectPythia/cookbook-actions/pull/119) for the temporary fix @jukent

**Comment by erogluorhan** [comment]
> Created a [PR](https://github.com/ProjectPythia/cookbook-actions/pull/119) for the temporary fix @jukent

Bad news, even after pinning to v44, it still [fails](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10888024774/job/30211596712). Not sure about what the actual issue is now.

**Comment by jukent** [comment]
Okay that's good to know though. I'm not sure either. I'll poke around and see if I come up with any ideas.

**Comment by erogluorhan** [comment]
As of now, `nightly-build` passes but `publish-site` fails; one main difference between those two is `build_from_code_artifact` being `false` with the former and `true` with latter, which leads to `actions/checkout@v4` being run or not, respectively, in the build-book.yaml

**Comment by jukent** [comment]
@erogluorhan it looks like metrics were last updated September 2nd, does that line up with the time of this failure occurring?
I think I explained the artifact download in our conversation on #459. I'm not sure why it would be failing now though.

**Comment by brian-rose** [comment]
I took a look to compare one of the [recent failed runs](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10888024774) to the [last successful run](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10658920655) of the `publish-site` action.

One difference I noticed: the list of extracted files during the "Download code artifact" step is not the same. The last successful run included files in the `.git/` subdirectory, e.g. [in the log here](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10658920655/job/29540732647#step:3:26). The recent failed run **did not include `.git/` files**, e.g. [here](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/10888024774/job/30211596712#step:3:26).

That could very well mean that the `tj-actions/changed-files` action is failing to recognize a valid git repository and can't see the revision history.

I suggest focusing on why this change occurred in the files captured in the artifact during the `automate-metrics` stage.

**Comment by brian-rose** [comment]
Further comment: I see [here](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) the comment that 
> With v4.4 and later, hidden files are excluded by default.

Version 4.4.0 of actions/upload-artifact was released three weeks ago: https://github.com/actions/upload-artifact/releases/tag/v4.4.0

Pretty sure this is the culprit.

**Comment by jukent** [comment]
Great detective work @brian-rose 
So if this is the culprit, we need to add `include-hidden-files` as `true` to the workflow?

**Comment by erogluorhan** [comment]
> Great detective work @brian-rose So if this is the culprit, we need to add `include-hidden-files` as `true` to the workflow?

Looks like so. Let us try it quick in the PR I had created.

Great catch, @brian-rose !

**Comment by jukent** [comment]
@erogluorhan made this PR before I saw your comment.
