### ISSUE TITLE
Enable team review requests for this repo

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#65]
Currently this repo has relatively rigid review requirements. Merging is blocked until 2 reviews are submitted by specific people listed as CODEOWNERS.

This is especially limiting for any changes in the top-most level of the repo, such as edits to the README file (e.g. #64), because the list of CODEOWNERS is small and somewhat arbitrary.

I suggest it would be better to adopt the GitHub Teams model that we are currently using for https://github.com/ProjectPythia/pythia-foundations

**Comment by kmpaul** [comment]
I'm looking into this with guidance from:

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team

**Comment by clyne** [comment]
We should revisit after we've had experience with "round robin" scheduler.
