### ISSUE TITLE
Add link to GitHub repository on top nav bar

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#74]
Change Pythia portal nav-bar html to include a drop-down button link to GitHub, the same as on the [foundations page](https://foundations.projectpythia.org/landing-page.html). Per a comment from @clyne on #69 

On the foundations page this is as simple as:
```
html:
  use_repository_button: true
```
in the `config.yaml` file.

It seems to be more complicated on the Portal as we are not using Jupyter book. Perhaps this is fixed in @kmpaul 's custom Sphinx theme for both books - but it would be nice to add this feature sooner.

**Comment by kmpaul** [comment]
@jukent:  It's probably more important to add this to the Foundations Book, anyway.  It's less important to add this to the portal.  In fact, I'm not sure we want it on the portal.

**Comment by jukent** [comment]
Why wouldn't we want it on the portal?

**Comment by kmpaul** [comment]
@jukent:  We want the GitHub link on any part of the site that we want outside contributions (i.e., via GitHub).  The Portal should be "shiny" and professional looking, which kinda requires curating the site's look and feel.  People can still contribute by finding the GitHub repository themselves, but I don't think we direct them to it explicitly.

**Comment by jukent** [comment]
Makes sense. I'll close this issue.
