### ISSUE TITLE
Enable automation of PR review assignments across repos

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#79]
Investigate and hopefully enable GitHub's "round robin" reviewer assignment for all repos as described here: 

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team#routing-algorithms

**Comment by clyne** [comment]
Need guidance from @kmpaul on how this working. @andersy005 believes the RR algo is tied to the teams: @ProjectPythia/education and @ProjectPythia/infrastructure. I.e. if one of these teams is tagged, automated RR scheduling will be used.

**Comment by dopplershift** [comment]
I think we can get this completely automated by [adding a team to `CODEOWNERS`](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners).
