### ISSUE TITLE
Facilitate contributions to external links gallery

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#80]
Each entry in the external links gallery requires a fixed set of information such as creator, email contact, affiliation, URL(s), and various content categorizations (e.g. science domain, media format, python package, etc.). We should facilitate, and to the degree we can, automate the process of gathering this information and ultimately generating a PR. A zeroth order step might be simply to put up a google form. Better, might be a templated issue that could automatically generate a PR from an issue. At the very least we need to document the information needed from contributors.

**Comment by clyne** [comment]
@andersy005, we had some discussion about this topic today. @jukent indicated that you have a GitHub template in the works for gathering up pertinent information to create a new entry for the external links gallery. Can you please provide an update on that? I'm revamping the contributor's guide(s) and would like to include discussion of this. Note, even if we can't yet automate the generation of a PR from the template at this point I'd still like to reference the template if it is ready. Thanks!

**Comment by jukent** [comment]
@clyne I'm talking to @andersy005 about this on Zulip. We hope to have something by the end of the day tomorrow. We'll let you know! Anderson is currently testing the GitHub actions necessary.

**Comment by clyne** [comment]
Coolio. Thanks for the  update! I'll put a placeholder in the contributor's doc.

**Comment by clyne** [comment]
@andersy005, just adding a comment here since the PR for this issue was merged for testing:

I think we need to give more guidance in the template than simply "Please fill out the template below". First, it would be good to have a description of what this template is for, possibly providing a link to the external links gallery. Second, I don't think it's clear to the contributor how to complete the template. How about instead of empty quotes after the keywords having something like 'YOUR_INPUT_GOES_HERE' or 'INSERT_YOUR_EMAIL_HERE'?
