### ISSUE TITLE
Link to Project Pythia Foundations directly from projectpythia.org

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#82]
Getting to the Project Pythia Foundations content is currently a little cumbersome. The "Project Pythia Foundations" menu item on projectpythia.org takes you to a page that provides a link that you can click on to get to https://foundations.projectpythia.org/landing-page.html. Can the menu item simply take you to https://foundations.projectpythia.org/landing-page.html

**Comment by brian-rose** [comment]
I think that would be fine as a "for now" solution. The main issue is that once you go over to the Foundations site, there is no longer any obvious navigation back to the main portal site.

I think we will be revisiting all of this once the new theme is in place. For now, I can submit a PR to make you change you describe.

**Comment by clyne** [comment]
It's not a big deal. Maybe we should just wait until after the new theme is in place.

**Comment by kmpaul** [comment]
I will handle this in the portal redesign.

**Comment by kmpaul** [comment]
Is this satisfied with the new portal design?

**Comment by brian-rose** [comment]
I think so! But let's wait until @clyne has a chance to chime in.

**Comment by clyne** [comment]
LGTM!
