### ISSUE TITLE
Make Submitting a Link to the External Gallery as User Friendly as Possible

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#98]
Per @clyne 's comments on #86 

We want to make the process as obvious as possible and document it as thoroughly as is helpful. I can take the lead on this, but there might be steps that I take for granted- so many eyes and minds in review will be helpful when the time comes.

This is a sub-issue related to #80

**Comment by andersy005** [comment]
Adding some relevant information/resources

- Issue template: https://github.com/ProjectPythia/.github/blob/main/.github/ISSUE_TEMPLATE/update-external-links-gallery.md
- Github workflow: https://github.com/ProjectPythia/projectpythia.github.io/blob/main/.github/workflows/update-external-links-gallery.yaml and https://github.com/ProjectPythia/projectpythia.github.io/blob/main/.github/workflows/collect-user-submission.py
